Updated write_reg_multi_bytes in nrf.py
list() generates a string array causing the following exception:

Traceback (most recent call last):
  File "nrf.py", line 183, in <module>
    main(*sys.argv[1:])
  File "nrf.py", line 152, in main
    nrf.setup(int(chan) if chan else 0)
  File "nrf.py", line 96, in setup
    self.write_reg_multi_bytes(RX_ADDR_P0, PROMISC_MAC[::-1], RX_PIPE_MAC_LEN)
  File "nrf.py", line 66, in write_reg_multi_bytes
    self.spi.xfer2([W_REGISTER | (REGISTER_MASK & reg)] + write)
TypeError: Non-Int/Long value in arguments: b6cbf368.